create extension if not exists pgcrypto;
create type public.estado_contenido as enum ('borrador','publicado','archivado');
create type public.rol_aplicacion as enum ('cliente','administrador','superadministrador');

create table public.perfiles(id uuid primary key references auth.users(id) on delete cascade,nombre_visible text check(char_length(nombre_visible)<=80),creado_en timestamptz not null default now(),actualizado_en timestamptz not null default now());
create table public.roles_usuario(usuario_id uuid primary key references auth.users(id) on delete cascade,rol public.rol_aplicacion not null default 'cliente',creado_en timestamptz not null default now());
create table public.tipos_producto(id uuid primary key default gen_random_uuid(),nombre text not null unique,slug text not null unique check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),creado_en timestamptz not null default now());
create table public.colecciones(id uuid primary key default gen_random_uuid(),nombre text not null,slug text not null unique,numero_edicion text not null,descripcion text not null,historia text not null,estado public.estado_contenido not null default 'borrador',publicado_en timestamptz,titulo_seo text,descripcion_meta text,creado_por uuid references auth.users(id),creado_en timestamptz not null default now(),actualizado_en timestamptz not null default now());
create table public.productos(id uuid primary key default gen_random_uuid(),tipo_producto_id uuid not null references public.tipos_producto(id),coleccion_id uuid references public.colecciones(id),nombre text not null,slug text not null unique,sku text unique,precio numeric(10,2) not null check(precio>=0),moneda text not null default 'PEN',descripcion text not null,materiales text,estado public.estado_contenido not null default 'borrador',es_limitado boolean not null default false,unidades_limitadas integer check(unidades_limitadas is null or unidades_limitadas>0),titulo_seo text,descripcion_meta text,creado_por uuid references auth.users(id),creado_en timestamptz not null default now(),actualizado_en timestamptz not null default now(),check(not es_limitado or unidades_limitadas is not null));
create table public.tallas_producto(id uuid primary key default gen_random_uuid(),producto_id uuid not null references public.productos(id) on delete cascade,talla text not null,stock integer not null default 0 check(stock>=0),unique(producto_id,talla));
create table public.publicaciones(id uuid primary key default gen_random_uuid(),titulo text not null,slug text not null unique,descripcion text not null,contenido text not null,estado public.estado_contenido not null default 'borrador',autor_id uuid references auth.users(id),publicado_en timestamptz,titulo_seo text,descripcion_meta text,creado_en timestamptz not null default now(),actualizado_en timestamptz not null default now());
create table public.imagenes(id uuid primary key default gen_random_uuid(),producto_id uuid references public.productos(id) on delete cascade,coleccion_id uuid references public.colecciones(id) on delete cascade,publicacion_id uuid references public.publicaciones(id) on delete cascade,identificador_publico text not null unique check(identificador_publico like 'skyblock-studio/%'),url_segura text not null check(url_segura like 'https://%'),tipo_recurso text not null default 'image',formato text not null,ancho integer not null check(ancho>0),alto integer not null check(alto>0),bytes integer not null check(bytes>0),texto_alternativo text not null,posicion integer not null default 0,subido_por uuid references auth.users(id),creado_en timestamptz not null default now(),check(num_nonnulls(producto_id,coleccion_id,publicacion_id)=1));
create table public.codigos_autenticidad(id uuid primary key default gen_random_uuid(),producto_id uuid not null references public.productos(id),coleccion_id uuid not null references public.colecciones(id),codigo_hmac bytea not null unique,ultimos_cuatro text not null,numero_serie text not null,estado text not null check(estado in('disponible','registrado','bloqueado','anulado')),activado_en timestamptz,creado_por uuid references auth.users(id),creado_en timestamptz not null default now(),unique(producto_id,numero_serie));
create table public.registros_autenticidad(id uuid primary key default gen_random_uuid(),codigo_id uuid not null unique references public.codigos_autenticidad(id),propietario_id uuid not null references auth.users(id),registrado_en timestamptz not null default now());
create table public.mensajes_contacto(id uuid primary key default gen_random_uuid(),nombre text not null,correo text not null,telefono text,asunto text not null,mensaje text not null,estado text not null default 'nuevo' check(estado in('nuevo','leido','archivado')),respondido_por uuid references auth.users(id),respondido_en timestamptz,creado_en timestamptz not null default now());
create table public.plantillas_correo(id uuid primary key default gen_random_uuid(),clave_plantilla text not null unique,asunto text not null,cuerpo_html text not null,actualizado_por uuid references auth.users(id),actualizado_en timestamptz not null default now());
create table public.registros_correo(id uuid primary key default gen_random_uuid(),identificador_proveedor text,estado text not null,clave_plantilla text,hash_destinatario text not null,codigo_error text,creado_en timestamptz not null default now());
create table public.registros_auditoria_admin(id bigint generated always as identity primary key,administrador_id uuid not null references auth.users(id),accion text not null,tipo_entidad text not null,entidad_id uuid,metadatos jsonb not null default '{}'::jsonb,creado_en timestamptz not null default now());

create index productos_publicos_idx on public.productos(estado,creado_en desc);create index productos_coleccion_idx on public.productos(coleccion_id);create index colecciones_publicas_idx on public.colecciones(estado,publicado_en desc);create index publicaciones_publicas_idx on public.publicaciones(estado,publicado_en desc);create index mensajes_estado_idx on public.mensajes_contacto(estado,creado_en desc);
create function public.es_administrador() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.roles_usuario where usuario_id=(select auth.uid()) and rol in('administrador','superadministrador'))$$;
revoke all on function public.es_administrador() from public;grant execute on function public.es_administrador() to authenticated;
create function public.establecer_actualizado_en() returns trigger language plpgsql set search_path='' as $$begin new.actualizado_en=now();return new;end$$;
create trigger perfiles_actualizados before update on public.perfiles for each row execute function public.establecer_actualizado_en();create trigger colecciones_actualizadas before update on public.colecciones for each row execute function public.establecer_actualizado_en();create trigger productos_actualizados before update on public.productos for each row execute function public.establecer_actualizado_en();create trigger publicaciones_actualizadas before update on public.publicaciones for each row execute function public.establecer_actualizado_en();

alter table public.perfiles enable row level security;alter table public.roles_usuario enable row level security;alter table public.tipos_producto enable row level security;alter table public.colecciones enable row level security;alter table public.productos enable row level security;alter table public.tallas_producto enable row level security;alter table public.publicaciones enable row level security;alter table public.imagenes enable row level security;alter table public.codigos_autenticidad enable row level security;alter table public.registros_autenticidad enable row level security;alter table public.mensajes_contacto enable row level security;alter table public.plantillas_correo enable row level security;alter table public.registros_correo enable row level security;alter table public.registros_auditoria_admin enable row level security;
revoke all on all tables in schema public from anon,authenticated;grant select on public.productos,public.tallas_producto,public.imagenes,public.colecciones,public.publicaciones,public.tipos_producto to anon,authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;

create policy productos_publicados on public.productos for select to anon,authenticated using(estado='publicado');create policy productos_administracion on public.productos for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy colecciones_publicadas on public.colecciones for select to anon,authenticated using(estado='publicado');create policy colecciones_administracion on public.colecciones for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy publicaciones_publicadas on public.publicaciones for select to anon,authenticated using(estado='publicado' and publicado_en<=now());create policy publicaciones_administracion on public.publicaciones for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy tipos_lectura_publica on public.tipos_producto for select to anon,authenticated using(true);create policy tipos_administracion on public.tipos_producto for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy tallas_lectura_publica on public.tallas_producto for select to anon,authenticated using(exists(select 1 from public.productos p where p.id=producto_id and p.estado='publicado'));create policy tallas_administracion on public.tallas_producto for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy imagenes_lectura_publica on public.imagenes for select to anon,authenticated using((producto_id is not null and exists(select 1 from public.productos p where p.id=producto_id and p.estado='publicado'))or(coleccion_id is not null and exists(select 1 from public.colecciones c where c.id=coleccion_id and c.estado='publicado'))or(publicacion_id is not null and exists(select 1 from public.publicaciones p where p.id=publicacion_id and p.estado='publicado')));create policy imagenes_administracion on public.imagenes for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy perfil_propio_lectura on public.perfiles for select to authenticated using((select auth.uid())=id);create policy perfil_propio_actualizacion on public.perfiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);create policy rol_propio_lectura on public.roles_usuario for select to authenticated using((select auth.uid())=usuario_id);create policy roles_administracion on public.roles_usuario for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));
create policy registros_propietario_lectura on public.registros_autenticidad for select to authenticated using(propietario_id=(select auth.uid()));create policy codigos_administracion on public.codigos_autenticidad for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));create policy mensajes_administracion on public.mensajes_contacto for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));create policy plantillas_administracion on public.plantillas_correo for all to authenticated using((select public.es_administrador())) with check((select public.es_administrador()));create policy registros_correo_administracion on public.registros_correo for select to authenticated using((select public.es_administrador()));create policy auditoria_administracion on public.registros_auditoria_admin for select to authenticated using((select public.es_administrador()));
